

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - "8086:8086"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - PORT=8086
      - SECRET_KEY=${SECRET_KEY}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    networks:
      - blog-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend/blog-site
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8086
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
    depends_on:
      - backend
    networks:
      - blog-network
    restart: unless-stopped

networks:
  blog-network:
    driver: bridge